"use client";
import * as React from "react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function OpportunityModerationPage() {
  const [data, setData] = React.useState<any>({ pending: [], recent: [], reports: [], events: [] }), [loading, setLoading] = React.useState(true), [error, setError] = React.useState("");
  const load = React.useCallback(() => fetch("/api/admin/opportunities").then(async (r) => { const d = await r.json(); if (r.ok) setData(d); else setError(d.error); }).finally(() => setLoading(false)), []);
  React.useEffect(() => { load(); }, [load]);
  const moderate = async (body: Record<string, unknown>) => { const r = await fetch("/api/admin/opportunities", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const d = await r.json(); if (r.ok) load(); else setError(d.error); };
  if (loading) return <p>Loading moderation queue…</p>;
  if (error && !data.pending.length) return <p role="alert" className="text-destructive">{error}</p>;
  return <div className="mx-auto max-w-7xl space-y-6"><div><h1 className="text-3xl font-bold">Job Opportunities moderation</h1><p className="text-muted-foreground">Review posts and reports. Conversation content is shown only for reported conversations.</p></div>{error && <p role="alert" className="text-destructive">{error}</p>}<Tabs defaultValue="pending"><TabsList><TabsTrigger value="pending">Pending ({data.pending.length})</TabsTrigger><TabsTrigger value="reports">Reports ({data.reports.filter((r: any) => ["open","reviewing"].includes(r.status)).length})</TabsTrigger><TabsTrigger value="recent">Recent</TabsTrigger><TabsTrigger value="audit">Audit</TabsTrigger></TabsList><TabsContent value="pending" className="space-y-4"><OpportunityRows rows={data.pending} moderate={moderate} pending /></TabsContent><TabsContent value="reports" className="space-y-4">{data.reports.map((report: any) => <ReportCard key={report.id} report={report} moderate={moderate} />)}</TabsContent><TabsContent value="recent" className="space-y-4"><OpportunityRows rows={data.recent} moderate={moderate} /></TabsContent><TabsContent value="audit" className="space-y-2">{data.events.map((event: any) => <div key={event.id} className="rounded-lg border p-3 text-sm"><Badge variant="outline" className="mr-2">{event.action}</Badge>{event.reason || "No additional note"}<p className="mt-1 text-xs text-muted-foreground">{new Date(event.created_at).toLocaleString("en-NG")}</p></div>)}</TabsContent></Tabs></div>;
}
function OpportunityRows({ rows, moderate, pending = false }: { rows: any[]; moderate: (body: Record<string, unknown>) => void; pending?: boolean }) { if (!rows.length) return <p className="rounded-xl border border-dashed p-10 text-center text-muted-foreground">Nothing here.</p>; return <>{rows.map((row) => <Card key={row.id}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-lg">{row.title}</CardTitle><p className="text-sm text-muted-foreground">{row.poster_name} · {row.category} · {row.country_code}</p></div><Badge className="capitalize">{row.status.replace("_", " ")}</Badge></div></CardHeader><CardContent className="space-y-3"><p className="whitespace-pre-wrap text-sm">{row.description}</p><div className="flex flex-wrap gap-2"><Button asChild variant="outline" size="sm"><Link href={`/opportunities/${row.id}`}>Inspect</Link></Button>{pending && <><Action label="Approve" onRun={(reason) => moderate({ action: "approve", opportunityId: row.id, reason })} /><Action label="Reject" destructive onRun={(reason) => moderate({ action: "reject", opportunityId: row.id, reason })} /></>}<Action label="Suspend" destructive onRun={(reason) => moderate({ action: "suspend", opportunityId: row.id, reason })} /><Action label="Suspend user" destructive onRun={(reason) => moderate({ action: "suspend_user", userId: row.owner_id, reason })} /></div></CardContent></Card>)}</>; }
function ReportCard({ report, moderate }: { report: any; moderate: (body: Record<string, unknown>) => void }) { return <Card><CardHeader><div className="flex items-center justify-between"><CardTitle className="text-lg capitalize">{report.reason.replaceAll("_", " ")}</CardTitle><Badge className="capitalize">{report.status}</Badge></div></CardHeader><CardContent className="space-y-3"><p className="text-sm">{report.explanation || "No explanation supplied."}</p><p className="text-xs text-muted-foreground">Private {report.entity_type} report · {new Date(report.created_at).toLocaleString("en-NG")}</p>{report.reported_messages?.length > 0 && <div className="space-y-2 rounded-lg border bg-muted/30 p-3"><p className="text-xs font-semibold">Reported conversation context</p>{report.reported_messages.map((message: any) => <p key={message.id} className="text-sm"><span className="text-xs text-muted-foreground">{new Date(message.created_at).toLocaleString("en-NG")}: </span>{message.message}</p>)}</div>}<div className="flex gap-2"><Action label="Resolve" onRun={(reason) => moderate({ action: "resolve_report", reportId: report.id, reason })} /><Action label="Dismiss" onRun={(reason) => moderate({ action: "dismiss_report", reportId: report.id, reason })} /></div></CardContent></Card>; }
function Action({ label, destructive, onRun }: { label: string; destructive?: boolean; onRun: (reason: string) => void }) { const [reason, setReason] = React.useState(""); return <div className="flex gap-1"><Input className="h-9 w-40" aria-label={`${label} reason`} placeholder="Reason or note" value={reason} onChange={(e) => setReason(e.target.value)} /><Button size="sm" variant={destructive ? "destructive" : "default"} onClick={() => { if (!destructive || window.confirm(`${label}?`)) onRun(reason); }}>{label}</Button></div>; }
