import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const read = (path) => readFileSync(path, "utf8");
const migration = read("supabase/migrations/20260804_owner_control_centre.sql");
const control = read("lib/control-centre.ts");
const owner = read("lib/owner-access.ts");
const workflow = read("lib/opportunity-workflow.ts");
const overviewApi = read("app/api/admin/control-centre/route.ts");
const createApi = read("app/api/admin/control-centre/opportunities/route.ts");
const jobApi = read("app/api/admin/control-centre/opportunities/[id]/route.ts");
const projectApi = read("app/api/opportunities/[id]/project/route.ts");
const conversationApi = read("app/api/opportunities/conversations/[id]/route.ts");
const messagesApi = read("app/api/opportunities/conversations/[id]/messages/route.ts");
const verificationApi = read("app/api/verification/route.ts");
const verificationAdminApi = read("app/api/admin/control-centre/verifications/route.ts");
const documentApi = read("app/api/admin/verification-document/route.ts");
const sidebar = read("components/layout/sidebar.tsx");
const badge = read("components/freelancer/verification-badge.tsx");

test("ordinary users cannot load protected Control Centre data", () => assert.match(overviewApi, /requireControlCentre[\s\S]*status: 403/));
test("Control Centre roles come from app_admins", () => { assert.match(control, /from\("app_admins"\)/); assert.match(control, /"owner", "admin", "moderator"/); });
test("no owner email is hard-coded", () => { assert.doesNotMatch(control + owner + overviewApi, /@[a-z0-9.-]+\.[a-z]{2,}/i); });
test("the private sidebar link is driven by an access check", () => { assert.match(sidebar, /controlCentreAccess/); assert.match(sidebar, /control-centre\?view=access/); });
test("the existing lifetime owner helper remains present", () => assert.match(owner, /app_admins[\s\S]*role[\s\S]*owner/));
test("the owner is automatically LeadPilot Verified", () => assert.match(migration, /app_admins WHERE user_id=p_user_id AND role='owner'/));
test("ordinary verification requires an approved record", () => assert.match(migration, /user_verifications WHERE user_id=p_user_id AND status='approved'/));
test("the badge has accessible LeadPilot Verified text", () => { assert.match(badge, /aria-label="LeadPilot Verified"/); assert.match(badge, /sr-only/); });
test("clients submit new jobs in pending review", () => assert.match(read("app/api/opportunities/route.ts"), /status: "pending_review"/));
test("server and database enumerate every managed job status", () => { for (const status of ["pending_review","changes_requested","approved","awaiting_assignment","assigned","in_progress","ready_for_review","revision_requested","completed","rejected","cancelled"]) { assert.match(workflow, new RegExp(status)); assert.match(migration, new RegExp(status)); } });
test("invalid database status transitions raise an exception", () => assert.match(migration, /INVALID_OPPORTUNITY_STATUS_TRANSITION/));
test("admin job decisions reject arbitrary actions", () => assert.match(jobApi, /Unknown control action/));
test("changes, rejection and cancellation require reasons", () => assert.match(jobApi, /Provide a clear reason/));
test("owner-managed jobs support real and manual clients", () => { assert.match(createApi, /clientUserId/); assert.match(createApi, /managedClientName/); });
test("client IDs are looked up instead of blindly trusted", () => assert.match(createApi, /user_profiles[\s\S]*selected client is unavailable/));
test("only owner or admin can assign", () => { assert.match(jobApi, /Only the owner or an administrator may assign workers/); assert.match(migration, /is_owner_or_admin\(p_actor_id\)/); });
test("the assignment RPC is service-role only", () => { assert.match(migration, /auth\.role\(\)<>'service_role'/); assert.match(migration, /REVOKE ALL ON FUNCTION public\.assign_opportunity_worker[\s\S]*authenticated/); });
test("duplicate active assignments are blocked by a partial unique index", () => assert.match(migration, /opportunity_assignments_one_active_idx[\s\S]*WHERE status IN/));
test("freelancers cannot assign themselves", () => { assert.match(migration, /freelancer_id <> assigned_by/); assert.match(migration, /p_freelancer_id IN \(p_actor_id,v_client\)/); });
test("suspended users and missing freelancer profiles cannot be assigned", () => { assert.match(migration, /FREELANCER_PROFILE_REQUIRED/); assert.match(migration, /FREELANCER_SUSPENDED/); });
test("assignment history is retained and cancellation is non-destructive", () => { assert.match(jobApi, /status: "cancelled"/); assert.doesNotMatch(jobApi, /from\("opportunity_assignments"\)\.delete/); });
test("assignment creates a project conversation", () => assert.match(migration, /INSERT INTO public\.opportunity_conversations[\s\S]*v_assignment/));
test("assignment adds client, freelancer and owner participants", () => { for (const role of ["client", "freelancer", "owner"]) assert.match(migration, new RegExp(`'${role}'`)); });
test("users cannot add themselves as project participants", () => assert.match(migration, /REVOKE ALL ON public\.opportunity_assignments[\s\S]{0,300}public\.opportunity_conversation_participants/));
test("conversation APIs require explicit active membership", () => { assert.match(conversationApi, /opportunity_conversation_participants/); assert.match(conversationApi, /membership\.left_at/); });
test("message senders are always the authenticated user", () => { assert.match(messagesApi, /sender_id: auth\.user\.id/); assert.doesNotMatch(messagesApi, /body\.sender/); });
test("message RLS does not grant blanket moderator access", () => { assert.match(migration, /Participants only messages[\s\S]*is_opportunity_conversation_participant/); assert.doesNotMatch(migration.match(/CREATE POLICY "Participants only messages"[\s\S]*?;/)?.[0] || "", /is_control_centre_member/); });
test("leaving or blocking disables continued sending", () => { assert.match(messagesApi, /membership\.left_at/); assert.match(messagesApi, /opportunity_blocks/); });
test("project actions are role allowlisted", () => { assert.match(projectApi, /roles: \["freelancer"/); assert.match(projectApi, /roles: \["client", "owner"\]/); assert.match(projectApi, /role !== "owner"/); });
test("project status and assignment histories are appended", () => { assert.match(projectApi, /opportunity_status_events/); assert.match(migration, /opportunity_assignments/); });
test("verification applications require a sufficiently complete freelancer profile", () => assert.match(verificationApi, /profile_completion_percentage[\s\S]*< 60/));
test("duplicate active verification applications are database blocked", () => assert.match(migration, /verification_applications_one_active_idx[\s\S]*pending','under_review','changes_requested/));
test("verification applications are rate limited", () => assert.match(verificationApi, /Verification application limit reached/));
test("the owner cannot create a duplicate verification application", () => { assert.match(verificationApi, /role === "owner"/); assert.match(verificationApi, /permanent owner role and cannot submit an application/); });
test("reviewers cannot decide their own application", () => assert.match(verificationAdminApi, /application\.user_id === auth\.user\.id/));
test("moderators cannot approve, revoke or restore badges", () => assert.match(verificationAdminApi, /Only the owner or an administrator may approve, revoke or restore/));
test("verification decisions enforce state transitions", () => assert.match(verificationAdminApi, /allowedByStatus/));
test("rejection, change and revocation decisions require reasons", () => assert.match(verificationAdminApi, /\["changes_requested", "reject", "revoke"\]/));
test("verification events record the authenticated reviewer", () => assert.match(verificationAdminApi, /moderator_id: auth\.user\.id/));
test("private documents accept safe types and enforce size limits", () => { assert.match(verificationApi, /image\/jpeg/); assert.match(verificationApi, /10 \* 1024 \* 1024/); });
test("private document access uses authorised short-lived signed URLs", () => { assert.match(documentApi, /requireControlCentre/); assert.match(documentApi, /createSignedUrl\(path, 60\)/); });
test("applicants cannot mutate protected verification decisions directly", () => { assert.match(migration, /REVOKE ALL ON public\.opportunity_assignments[\s\S]*public\.verification_applications/); assert.match(migration, /GRANT SELECT ON public\.opportunity_assignments/); });
test("legacy verified profiles are preserved through trusted backfill", () => assert.match(migration, /INSERT INTO public\.user_verifications[\s\S]*verification_status='verified'[\s\S]*ON CONFLICT\(user_id\) DO NOTHING/));
test("private owner notes are isolated from the publicly selectable jobs table", () => { assert.match(migration, /CREATE TABLE IF NOT EXISTS public\.opportunity_owner_notes/); assert.doesNotMatch(migration.match(/ALTER TABLE public\.opportunities[\s\S]*?;/)?.[0] || "", /private_owner_notes/); });
test("the migration is repeatable and preserves existing core tables", () => { for (const table of ["opportunity_assignments","opportunity_status_events","opportunity_owner_notes","opportunity_conversation_participants","verification_applications","user_verifications","verification_events"]) assert.match(migration, new RegExp(`CREATE TABLE IF NOT EXISTS public\\.${table}`)); assert.doesNotMatch(migration, /DROP TABLE|TRUNCATE/); });
