export const WEBSITE_PURPOSES = [
  "Sell products",
  "Promote services",
  "Generate leads",
  "Accept bookings",
  "Display a portfolio",
  "Receive customer enquiries",
  "Show business information",
  "Build a personal brand",
  "Create a landing page",
  "Create an online store",
  "Create a marketplace",
];
export const WEBSITE_PAGES = [
  "Home",
  "About",
  "Services",
  "Products",
  "Shop",
  "Portfolio",
  "Pricing",
  "Booking",
  "Contact",
  "FAQ",
  "Testimonials",
  "Blog",
  "Login",
  "Sign-up",
  "User dashboard",
  "Admin dashboard",
  "Privacy Policy",
  "Terms of Service",
  "Refund Policy",
];
export const WEBSITE_FEATURES = [
  "Contact form",
  "WhatsApp button",
  "Live chat",
  "AI chatbot",
  "Appointment booking",
  "Online payment",
  "Subscription payments",
  "Shopping cart",
  "User accounts",
  "Admin panel",
  "Product management",
  "Order management",
  "Reviews and ratings",
  "Search",
  "Filters",
  "File uploads",
  "Email notifications",
  "Social-media links",
  "Location map",
  "Newsletter",
  "Analytics",
  "Dark mode",
  "Multiple languages",
  "Mobile app preparation",
];
export const DESIGN_STYLES = [
  "Modern",
  "Premium",
  "Minimal",
  "Corporate",
  "Colourful",
  "Elegant",
  "Playful",
  "Futuristic",
  "Professional",
  "Luxury",
  "Friendly",
];
export const TECHNOLOGIES = [
  "No preference",
  "Next.js",
  "React",
  "HTML, CSS and JavaScript",
  "WordPress",
  "Shopify",
  "Bubble",
  "Flutter",
  "Supabase",
  "Firebase",
  "Another technology",
];
export const TECH_REQUIREMENTS = [
  "Database",
  "Authentication",
  "Payment integration",
  "Admin dashboard",
  "API integration",
  "Hosting instructions",
  "Mobile responsiveness",
  "SEO",
  "Accessibility",
  "Security controls",
];
